### ISSUE TITLE
Disable autocomplete

### ISSUE THREAD

**Issue by weberam2** [R-nvim/cmp-r#11]
Hello!

I'm not sure this is the place to ask this question.

I am using LazyVim's R Extra package [R Extra](https://www.lazyvim.org/extras/lang/r)

When I type "`" in insert mode, it autocompletes and creates a code chunk.

How can I disable this?

Again, maybe it's actually being declared somewhere else, but I thought it would be worth it to ask the question here

**Comment by jalvesaq** [comment]
You can configure this in `R.nvim`, not `cmp-r`. Please, see the option `rmdchunk` in `R.nvim` documentation.

**Comment by weberam2** [comment]
Thank you!

In Lazyvim, in my plugins folder, I made an R.lua file:

```
return {
  "R-nvim/R.nvim",
  opts = {
    rmdchunk = 0,
  },
}
```

In case anyone else has this issue
