### ISSUE TITLE
Completion not showing in some function

### ISSUE THREAD

**Issue by PMassicotte** [R-nvim/cmp-r#3]
I was exploring the new release of `ggplot2`  (https://www.tidyverse.org/blog/2024/02/ggplot2-3-5-0-axes/) and noticed that completion was not working for some function, whereas `ray-x/lsp_signature.nvim` (https://github.com/ray-x/lsp_signature.nvim) is showing it.

![image](https://github.com/R-nvim/cmp-r/assets/4519221/34a10fa1-967b-4d72-856a-bcb18febed24)

Do you experience the same situation?

**Comment by jalvesaq** [comment]
The signature box above the cursor is not coming from R.nvim.
I'm trying to clean the code because it is geared towards the legacy omni-completion, and perhaps, the issue will be fixed by the refactored completion system.

**Comment by PMassicotte** [comment]
yes the box comes from another plug. It was just to show that some others plugins were able to show arguments.
