### ISSUE TITLE
Completion error when an object inherits from multiple classes

### ISSUE THREAD

**Issue by PMassicotte** [R-nvim/cmp-r#6]
The error occurs here:

https://github.com/R-nvim/R.nvim/blob/ffc1d52a2b08ea542d2c3c484eea3c7fd9ee4b11/nvimcom/R/misc.R#L426-L430

when an object inherits from multiple classes, for example a `tibble`:

`"tbl_df"     "tbl"        "data.frame"`

Will produce this error when autocomplete is triggered:

```r
Error in exists(mname) : first argument has length > 1
```

This works

```r
mtcars |>
  mutate()
```

Because 

```r
r$> class(mtcars)
[1] "data.frame"
```

This will not work because

```r
mt <- as_tibble(mtcars)

mt |>
  mutate()

r$> class(mt)
[1] "tbl_df"     "tbl"        "data.frame"
```

I guess we could use  `mname <- paste0(fname, objclass[1])` instead of `mname <- paste0(fname, objclass)`

**Comment by PMassicotte** [comment]
Or something like this:

```r
nvim.getmethod <- function(fname, objclass) {
    mname <- paste0(fname, objclass)
    if (any(lapply(mname, exists)) && is.function(get(mname)))
        return(mname)
    return(fname)
}
```

**Comment by jalvesaq** [comment]
In your second solution, does `is.function(get(mname))` work? Shouldn't it also be passed to `any()`?

```r
any(sapply(sapply(mname, get), is.function))
```

Maybe the function `nvim.getmethod()` should be rewritten, using `hasMethod()` or `existsMethod()`... But I could find a way of using them correctly.

A sample code to test it can be:

```r
library(tidyverse)
mt <- tibble(mtcars)
print(mt, )
```

According to the R documentation for `tibble::print.tbl`, the menu for completion of arguments after the comma should be:

```
x
width =
...
n =
max_extra_cols =
max_footer_lines =
```

**Comment by PMassicotte** [comment]
1. Yes it worked, I implemented it locally, and this fixed the error. Maybe we can also add what you suggest for `is.function`.
2. `hasMethod()` sounds good!

**Comment by jalvesaq** [comment]
These don't work:

```r
hasMethod("print", "tbl")
existsMethod("print", "tbl")
hasMethod("print", "tbl_df")
existsMethod("print", "tbl_df")
```

This works (the method `print.tbl` is listed):

```r
methods("print")
```

Then, running `\rh` over `print.tbl` works, but `args(print.tbl)` doesn't work.

If we can't find a way of completing the arguments according to the method that R will apply, it might be better to give up and show in the completion menu whatever `args(print)` returns.

**Comment by jalvesaq** [comment]
> Yes it worked, I implemented it locally, and this fixed the error.

Good! But if we can't fix the feature itself (display arguments according to the appropriate method), we don't need the function `nvim.getmethod()` at all.

**Comment by PMassicotte** [comment]
> Then, running `\rh` over `print.tbl` works, but `args(print.tbl)` doesn't work.

Might be difficult to fix :)

**Comment by jalvesaq** [comment]
Should I make a pull request to remove the feature, or do you have any hope of fixing it?
