### ISSUE TITLE
Completion rendering appears broken

### ISSUE THREAD

**Issue by lokesh-krishna** [R-nvim/cmp-r#7]
Completions are sometimes put descriptions in the same line as the title and this breaks the description box that appears to the side. I'm not sure if I'm using the right terms here but attaching screenshots to show what's happening.

How can I identify whether this is an issue with cmp-r or some other component of my setup? Lua completions seem to show up fine and there aren't any other languages I use. 

![grim-2024-03-09-11-00-31](https://github.com/R-nvim/cmp-r/assets/20235646/4be6f741-4038-4b2e-a661-28268b4a08da)
![grim-2024-03-09-10-54-29](https://github.com/R-nvim/cmp-r/assets/20235646/df226c2a-3147-416b-8c94-8b103a0e39b1)

**Comment by jalvesaq** [comment]
I typed the code exactly as in your images, but I can't replicate the bug.

**Comment by lokesh-krishna** [comment]
This is the file I'm using: [data_vis.R](https://paste.sr.ht/~low-key/90d179bdb0052daa09964f07084c4a5715677b8c)

Opening this and going to the bottom, just doing `diamonds |> gg` brings up the completion menu with this issue. I tried on Neovim 0.9.5 and on Neovim Nightly and had the same thing happen in both places. Could any other plugins be interacting with this to create this situation? 

List of my currently installed plugins:  [Nvim Plugins](https://paste.sr.ht/~low-key/3faa401a66eca5b6fc1ce722c6ecf384e8942630)

**Comment by lokesh-krishna** [comment]
Tried it with the corresponding branch from `cmp-r` but still seem to have the same issue. I'm also really confused about what might be going on here. 

![image](https://github.com/R-nvim/cmp-r/assets/20235646/e84071f4-761b-478a-9372-defd82ab17c1)

Should I close it if it seems to stem from something else?

**Comment by jalvesaq** [comment]
These items with a `~` at the end don't come from `R.nvim`/`cmp-r`. Perhaps they are from the `languageserver`, if you have installed it. I have this is part of my `cmp` config:

```lua
                local kind_icons = {
                    Text = "",
                    Method = "󰆧",
                    Function = "󰊕",
                    Constructor = "󱢌",
                    Field = "󰽐",
                    Variable = "α",
                    Class = "󰠱",
                    Interface = "",
                    Module = "",
                    Property = "󰜢",
                    Unit = "",
                    Value = "󰎠",
                    Enum = "",
                    Keyword = "󰌋",
                    Snippet = "",
                    Color = "󰏘",
                    File = "󰈙",
                    Reference = "",
                    Folder = "󰉋",
                    EnumMember = "",
                    Constant = "󰏿",
                    Struct = "",
                    Event = "",
                    Operator = "󰆕",
                    TypeParameter = "",
                }

             --- Some lines below ---
                    formatting = {
                        fields = {'abbr', 'kind', 'menu'},
                        format = function(entry, vim_item)
                            -- Kind icons
                            vim_item.kind = string.format('%s', kind_icons[vim_item.kind])
                            -- Source
                            vim_item.menu = ({
                                otter = "o",
                                nvim_lsp = '',
                                nvim_lua = 'L',
                                luasnip = '',
                                buffer = '﬘',
                                cmdline = ":",
                                path = '',
                                cmp_zotcite = 'Z',
                                cmp_r = 'R'
                            })[entry.source.name] or entry.source.name
                            return vim_item
                        end
                    },
```

This way, the `menu` part of the menu is the letter "R" if the source is `cmp_ r`. Then, I know where the completion is coming from.

I have this in my `~.Rprofile` to inhibit completions from the `languageserver`:

```r
options(languageserver.server_capabilities = list(completionProvider = FALSE,
    completionItemResolve = FALSE))

**Comment by lokesh-krishna** [comment]
Thank you so much for sticking with me for this long! The cmp settings helped me confirm that those problematic completions were indeed from the language server. 

I did have the completions inhibition bit in my projects' `.Rprofile` but not in my  `~/.Rprofile`. Adding it there is what stopped those completions from finally showing up. 

Once again, thank you for everything!
